name: Secrets Secrets Hurt Someone

on: [push]

# Just a change to make a commit

jobs:
  shh:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Level
        run: echo ${{ secrets.SHH_REPO }}
      - name: Environment Level
        run: echo ${{ secrets.SHH_ENV }}
