name: Secrets Secrets Hurt Someone

on: [push]

# Just a change to make a commit

jobs:
  shh:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Level
        run: echo ${{ secrets.SHH_REPO }} | sed 's/./& /g'
        # I'm not sure how do get this, but I suppose the action
        # isn't running in the Staging environment anyway.
      - name: Environment Level
        run: echo ${{ secrets.SHH_ENV }} | sed 's/./& /g'
