name: Workflow Commands

on: [push]

jobs:
  command-job:
    runs-on: ubuntu-latest
    steps:
      - name: group logging
        run: |
          echo ::group::My Group Message
          echo msg 1
          echo msg 2
          echo ::endgroup::
      - name: Add var to env
        run: echo MY_VAL=dudesweet >> $GITHUB_ENV
      - name: Read var from env
        run: |
          echo GITHUB_ENV: $GITHUB_ENV
          echo MY_VAL: $MY_VAL
